name: Unit Test

# Controls when the action will run.
on: [ pull_request ]

env:
    YANDEX_STORAGE_KEY: ${{ secrets.YANDEX_STORAGE_KEY }}
    YANDEX_STORAGE_SECRET: ${{ secrets.YANDEX_STORAGE_SECRET }}

jobs:
  test:
    name: PHP Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0' ]
    steps:
      - uses: EggheadsSolutions/ci-php-unit-test@v1
        with:
          php-version: ${{ matrix.php-versions }}
          mysql: no
          redis: no
          clickhouse: yes
          use-repository-config: yes
          post-install-cmd: no
